### ISSUE TITLE
Put cacheable to AuraEnabled annotation to enable wiring the feature flag

### ISSUE THREAD

**Issue by JackVeromeev** [pgonzaleznetwork/salesforce-feature-flags#1]

**Comment by pgonzaleznetwork** [comment]
@JackVeromeev I don't understand what you are asking. Can you please include more info?

**Comment by JackVeromeev** [comment]
Hi @pgonzaleznetwork 
Sorry, I missed to finish the issue name
Would it be better to put `cacheable=true` to AuraEnabled method?
This way the lwc dev can eadily wire the value of the feature flag into the component
