### ISSUE TITLE
Distribute releases as unlocked and/or (preferred) managed packages

### ISSUE THREAD

**Issue by noerremark** [pgonzaleznetwork/salesforce-feature-flags#4]
Nice framework! One thing I'd like is to distribute releases as a package, rather than code. Other good open source frameworks like [NebulaLogger](https://github.com/jongpie/NebulaLogger) does this, and in many projects it's the prefered way to use open source. The only other way is to adopt the source in various forms, and that always leads to modifications not contributed to the public.
By having a package changes are minimized and package versions controlled.

**Comment by pgonzaleznetwork** [comment]
As discussed on LinkedIn, feel free to create this is a namespaced org and add the package details to the repo.
